name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hl7fhir/ig-publisher-base:latest
    steps:
      - name: Debug
        run: whoami && env && pwd && ls -la && groups && mkdir .fhir-package-cache
      - name: With latest sushi
        run: >
         git config --global --add safe.directory /home/publisher/bin/ig-publisher-scripts &&
         /home/publisher/bin/with-latest-sushi.sh &&
         which sushi &&
         sushi --version
      - name: Debug 2
        run: ls -la /home/publisher/.node/bin && which sushi && sushi --version && pwd && ls -la
      - name: Update the image to the latest publisher
        run: curl -L https://github.com/HL7/fhir-ig-publisher/releases/latest/download/publisher.jar -o ./publisher.jar --create-dirs
      - name: Checkout medigree/core to ./core
        uses: actions/checkout@v2
        with:
          repository: medigree/core
          path: core

      - name: Checkout HL7/fhir-ig-history-template to ./history-template
        uses: actions/checkout@v2
        with:
          repository: HL7/fhir-ig-history-template
          path: history-template

      - name: Checkout medigree/current-publication to ./webroot
        uses: actions/checkout@v2
        with:
          repository: medigree/current-publication
          path: webroot

      - name: Checkout FHIR/ig-registry to ./ig-registry
        uses: actions/checkout@v2
        with:
          repository: FHIR/ig-registry
          path: ig-registry

      - name: Run publisher command
        run: java -jar ./publisher.jar publisher -ig core -package-cache-folder ./fhir-package-cache

      - name: Run publisher command for publishing release
        run: java -Dfile.encoding=UTF-8 -jar publisher.jar -go-publish -package-cache-folder ./fhir-package-cache -source core -web $(pwd)/webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template -templates $(pwd)/webroot/templates
