name: CI

on:
  push:
    branches-ignore:
      - 'gh-pages'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: hl7fhir/ig-publisher-base:latest
    steps:
      - name: Gather prerequisites
        run: >
          gosu publisher /home/publisher/bin/with-latest-sushi.sh &&
          _updatePublisher.sh -y

      - name: Checkout medigree/core to ./core
        uses: actions/checkout@v2
        with:
          repository: medigree/core
          path: core

      - name: Checkout HL7/fhir-ig-history-template to ./history-template
        uses: actions/checkout@v2
        with:
          repository: HL7/fhir-ig-history-template
          path: history-template

      - name: Checkout medigree/current-publication to ./webroot
        uses: actions/checkout@v2
        with:
          repository: medigree/current-publication
          path: webroot

      - name: Checkout FHIR/ig-registry to ./ig-registry
        uses: actions/checkout@v2
        with:
          repository: FHIR/ig-registry
          path: ig-registry

      - name: Run publisher command
        run: java -jar ./input-cache/publisher.jar publisher -ig core

      - name: Run publisher command for publishing release
        run: java -Dfile.encoding=UTF-8 -jar ./input-cache/publisher.jar -go-publish -source core -web $(pwd)/webroot -registry ./ig-registry/fhir-ig-list.json -history ./history-template -templates $(pwd)/webroot/templates
